version: "3.9"
services:
  bot:
    build: .
    image: gerovms/british_parliament_bot:latest
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./results:/app/results
    networks:
      - bot_network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot_network

volumes:
  db_data:

networks:
  bot_network:
