version: "3.9"
services:
  bot:
    image: gerovms/british_parliament_bot:latest
    env_file:
      - ./.env
    volumes:
      - ./results:/app/results
      - ./wait-for-postgres.sh:/app/wait-for-postgres.sh
    depends_on:
      - db
    command: ["sh", "/app/wait-for-postgres.sh", "db", "python", "-m", "bot"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: