version: "3.9"
services:
  bot:
    build: .
    image: gerovms/british_parliament_bot:latest
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - worker
    volumes:
      - ./results:/app/results
    networks:
      - bot_network
  worker:
    build: .
    image: gerovms/british_parliament_bot:latest
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - bot_network
    command: celery -A tasks worker --loglevel=info
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot_network

  redis:
    image: redis:7.2
    restart: always
    environment:
      REDIS_MAXMEMORY: ${REDIS_MAXMEMORY}
      REDIS_POLICY: ${REDIS_POLICY}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    command:
      [
        "redis-server",
        "--port", "${REDIS_PORT}",
        "--maxmemory", "${REDIS_MAXMEMORY}",
        "--maxmemory-policy", "${REDIS_POLICY}"
      ]
    volumes:
      - redis_data:/data
    networks:
      - bot_network

volumes:
  db_data:
  redis_data:

networks:
  bot_network:
