version: "3.9"
services:
  bot:
    build: .
    image: gerovms/british_parliament_bot:latest
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    volumes:
      - ./results:/app/results
    networks:
      - bot_network
  worker:
    image: gerovms/british_parliament_bot:latest
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - bot_network
    command: ["celery", "-A", "app.tasks.tasks.celery_app", "worker", "--loglevel=info"]
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot_network

  redis:
    image: redis:7.2
    restart: always
    env_file:
      - ./.env
    command:
      [
        "redis-server",
        "--port", "${REDIS_PORT}",
        "--maxmemory", "${REDIS_MAXMEMORY}",
        "--maxmemory-policy", "${REDIS_POLICY}"
      ]
    volumes:
      - redis_data:/data
    networks:
      - bot_network

volumes:
  db_data:
  redis_data:

networks:
  bot_network:
